### ISSUE TITLE
New buttons

### ISSUE THREAD

**Issue by naps62** [andrefs/botoes.co#1]
The community demands updates!

Is this project dead?

**Comment by joaojusto** [comment]
:+1: on @naps62 request.
This project doesn't even have a decent API, what makes impossible to integrate this with slack.

**Comment by andrefs** [comment]
You guys ever heard about this funny little thing called Pull Requests?
Anyway, this project is only a static page with links. You should probably be whining at https://github.com/andrefs/node-sb-builder ;)
